name: Deploy to Stage Environment

on:
  push:
    branches:
      - staging

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    EKS_CLUSTER: ${{ secrets.EKS_CLUSTER_NAME_STAGE }}

jobs:
    build-and-deploy:
        name: Build, Push and Deploy
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:

            
                    - service: product-service
                      path: app/go-services/product-service
                      lang: go
                    - service: payment-service
                      path: app/go-services/payment-service
                      lang: go
                    - service: user-service
                      path: app/go-services/user-service
                      lang: go



                    - service: cart-service
                      path: app/node-services/cart-service
                      lang: node
                    - service: shipping-service
                      path: app/node-services/shipping-service
                      lang: node
                    - service: order-service
                      path: app/python-services/order-service
                      lang: python



                    - service: inventory-service
                      path: app/python-services/inventory-service
                      lang: python
                    - service: notification-service
                      path: app/python-services/notification-service
                      lang: python

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}


            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1


            - name: Build, tag and push Docker image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $ECR_REGISTRY/${{ matrix.service }}:${IMAGE_TAG-staging} ${{ matrix.path }}
                docker push $ECR_REGISTRY/${{ matrix.service }}:${IMAGE_TAG-staging}



            - name: Update Kube config
              run: |
                aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

                - name: Deploy to EKS
                env:
                    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    IMAGE_TAG: ${{ github.sha }}
                run: |
                    kubectl set image deployment/${{ matrix.service }} ${{matrix.service}}=$ECR_REGISTRY/${{matrix.service}}:${IMAGE_TAG-staging} --namespace=staging
